#!/bin/bash

#指定U盘
if [[ "$1" = "" ]]; then
	echo 'Useage: mntfs [Volume Name] Mount a NTFS USB Disk'
	echo '        mntfs [Volume Name] [off]  Unmount a NTFS USB Disk'
	exit
fi

#挂载点
MOUNT_DIR=/Users/$USER/Desktop/$1


#获取 Device Node Info
DEVICE_NODE_INFO=`diskutil info /Volumes/$1 | grep 'Device Node:'`

if [[ "$DEVICE_NODE_INFO" = "" ]]; then
	echo The disk $1 not exist.
	echo Please check your dist again.
	exit
fi

#获取 Device Node
DEVICE_NODE=${DEVICE_NODE_INFO#*Device Node:}

#取消挂载U盘
if [[ "$2" = "off" ]]; then
	#推出u盘
	diskutil eject ${NFTS_DIR}

	rm -rf ${NFTS_DIR}
fi


#建立挂载点
`mkdir -p ${MOUNT_DIR}`

#推出u盘
diskutil eject ${DEVICE_NODE}

#挂载U盘
sudo mount_ntfs -o rw,nobrowse ${DEVICE_NODE} ${MOUNT_DIR}

echo 'Mount Disk Sucess!!' 




 